{ pkgs ? import <nixpkgs> {} }:

pkgs.mkShell {
  buildInputs = with pkgs; [
    ant
    autoconf
    capstone
    gnumake
    maven
    pandoc
    pigz
    temurin-bin-21
    temurin-bin-25
  ];

  ANT_HOME="${pkgs.ant}/share/ant";
  BOOT_JDK_HOME="${pkgs.temurin-bin-25}";
  CAPSTONE_HOME="${pkgs.capstone}";
  IGV_JDK_HOME="${pkgs.temurin-bin-21}";
  MAVEN_HOME="${pkgs.maven}";

  shellHook = ''
    # Define here to get $HOME resolved
    export STUB_DIR="$HOME/Library/Caches/openjdk-build-stubs";


    mkdir -p "$STUB_DIR"
    export OPENJDK_STUB_DIR="$STUB_DIR"

    # Create stub-mig.sh
    cat > "$STUB_DIR/stub-mig.sh" << 'STUB_MIG_EOF'
#!/bin/bash
# Stub mig script to bypass mig requirement
# Generates minimal stub implementations for mach_exc interfaces

# Parse arguments to find output files
SERVER_FILE=""
USER_FILE=""
HEADER_FILE=""

while [[ $# -gt 0 ]]; do
  case $1 in
    -server)
      SERVER_FILE="$2"
      shift 2
      ;;
    -user)
      USER_FILE="$2"
      shift 2
      ;;
    -header)
      HEADER_FILE="$2"
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

# Create header file with minimal declarations
if [ -n "$HEADER_FILE" ]; then
  cat > "$HEADER_FILE" << 'EOF'
/* Stub header generated by stub-mig.sh */
#ifndef _mach_exc_server_
#define _mach_exc_server_

#include <mach/mach.h>
#include <mach/message.h>

#ifdef __cplusplus
extern "C" {
#endif

extern boolean_t mach_exc_server(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

#ifdef __cplusplus
}
#endif

#endif /* _mach_exc_server_ */
EOF
fi

# Create server file with stub implementation
if [ -n "$SERVER_FILE" ]; then
  cat > "$SERVER_FILE" << 'EOF'
/* Stub server implementation generated by stub-mig.sh */
#include <mach/mach.h>
#include <mach/message.h>

/* Stub implementation of mach_exc_server */
boolean_t mach_exc_server(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP) {
    /* This is a stub - not actually used in headless JDK build */
    return FALSE;
}
EOF
fi

# Create user file with stub implementation
if [ -n "$USER_FILE" ]; then
  cat > "$USER_FILE" << 'EOF'
/* Stub user implementation generated by stub-mig.sh */
#include <mach/mach.h>

/* User stubs - not implemented */
EOF
fi

exit 0
STUB_MIG_EOF
    chmod +x "$STUB_DIR/stub-mig.sh"

    # Create stub-setfile.sh
    cat > "$STUB_DIR/stub-setfile.sh" << 'STUB_SETFILE_EOF'
#!/bin/bash
# Stub SetFile script to bypass SetFile requirement
# SetFile sets Finder attributes on macOS, which are not essential for JDK functionality

# Simply exit successfully without doing anything
# The -a B flag sets the "Bundle" attribute which is purely cosmetic
exit 0
STUB_SETFILE_EOF
    chmod +x "$STUB_DIR/stub-setfile.sh"

    # Create stub-setfile.sh
    cat > "$STUB_DIR/stub-setfile.sh" << 'STUB_SETFILE_EOF'
#!/bin/bash
# Stub SetFile script to bypass SetFile requirement
# SetFile sets Finder attributes on macOS, which are not essential for JDK functionality

# Simply exit successfully without doing anything
# The -a B flag sets the "Bundle" attribute which is purely cosmetic
exit 0
STUB_SETFILE_EOF
    chmod +x "$STUB_DIR/stub-setfile.sh"

    echo "ANT_HOME set to $ANT_HOME"
    echo "BOOT_JDK_HOME set to $BOOT_JDK_HOME"
    echo "CAPSTONE_HOME set to $CAPSTONE_HOME"
    echo "IGV_JDK_HOME set to $IGV_JDK_HOME"
    echo "MAVEN_HOME set to $MAVEN_HOME"
    echo "STUB_DIR set to $STUB_DIR"

    unset SOURCE_DATE_EPOCH
    echo "Unsetting SOURCE_DATE_EPOCH to avoid errors running tests"
  '' ;
}
