{ pkgs ? import <nixpkgs> {}
, jtreg ? null  # Optional: path to jtreg installation
}:

pkgs.mkShell {
  buildInputs = with pkgs; [
    autoconf
    gnumake
    temurin-bin-25
    git  # for cloning googletest
  ];

  shellHook = ''
    # Fix SOURCE_DATE_EPOCH for jar date validation
    # Nix sets it to 315532800 (1980-01-01 00:00:00) but jar needs >= 1980-01-01 00:00:02
    export SOURCE_DATE_EPOCH=315532802

    export BOOT_JDK_HOME="${pkgs.temurin-bin-25}"

    # Create directory for stub scripts in cache
    STUB_DIR="$HOME/Library/Caches/openjdk-build-stubs"
    mkdir -p "$STUB_DIR"
    export OPENJDK_STUB_DIR="$STUB_DIR"

    # Set up googletest for native testing
    GTEST_DIR="$HOME/Library/Caches/openjdk-googletest"
    if [ ! -d "$GTEST_DIR" ]; then
      echo "Cloning googletest 1.14.0..."
      git clone --depth 1 --branch v1.14.0 https://github.com/google/googletest.git "$GTEST_DIR" 2>/dev/null || true

      # Patch gtest-printers.h to fix char16_t implicit conversion warning
      if [ -f "$GTEST_DIR/googletest/include/gtest/gtest-printers.h" ]; then
        echo "Patching googletest for clang character-conversion warnings..."
        sed -i.bak 's/PrintTo(ImplicitCast_<char32_t>(c), os);/PrintTo(static_cast<char32_t>(c), os);/g' \
          "$GTEST_DIR/googletest/include/gtest/gtest-printers.h"
      fi
    fi
    if [ -d "$GTEST_DIR" ]; then
      export GTEST_HOME="$GTEST_DIR"
    fi

    # Create stub-mig.sh
    cat > "$STUB_DIR/stub-mig.sh" << 'STUB_MIG_EOF'
#!/bin/bash
# Stub mig script to bypass mig requirement
# Generates minimal stub implementations for mach_exc interfaces

# Parse arguments to find output files
SERVER_FILE=""
USER_FILE=""
HEADER_FILE=""

while [[ $# -gt 0 ]]; do
  case $1 in
    -server)
      SERVER_FILE="$2"
      shift 2
      ;;
    -user)
      USER_FILE="$2"
      shift 2
      ;;
    -header)
      HEADER_FILE="$2"
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

# Create header file with minimal declarations
if [ -n "$HEADER_FILE" ]; then
  cat > "$HEADER_FILE" << 'EOF'
/* Stub header generated by stub-mig.sh */
#ifndef _mach_exc_server_
#define _mach_exc_server_

#include <mach/mach.h>
#include <mach/message.h>

#ifdef __cplusplus
extern "C" {
#endif

extern boolean_t mach_exc_server(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

#ifdef __cplusplus
}
#endif

#endif /* _mach_exc_server_ */
EOF
fi

# Create server file with stub implementation
if [ -n "$SERVER_FILE" ]; then
  cat > "$SERVER_FILE" << 'EOF'
/* Stub server implementation generated by stub-mig.sh */
#include <mach/mach.h>
#include <mach/message.h>

/* Stub implementation of mach_exc_server */
boolean_t mach_exc_server(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP) {
    /* This is a stub - not actually used in headless JDK build */
    return FALSE;
}
EOF
fi

# Create user file with stub implementation
if [ -n "$USER_FILE" ]; then
  cat > "$USER_FILE" << 'EOF'
/* Stub user implementation generated by stub-mig.sh */
#include <mach/mach.h>

/* User stubs - not implemented */
EOF
fi

exit 0
STUB_MIG_EOF
    chmod +x "$STUB_DIR/stub-mig.sh"

    # Create stub-setfile.sh
    cat > "$STUB_DIR/stub-setfile.sh" << 'STUB_SETFILE_EOF'
#!/bin/bash
# Stub SetFile script to bypass SetFile requirement
# SetFile sets Finder attributes on macOS, which are not essential for JDK functionality

# Simply exit successfully without doing anything
# The -a B flag sets the "Bundle" attribute which is purely cosmetic
exit 0
STUB_SETFILE_EOF
    chmod +x "$STUB_DIR/stub-setfile.sh"

    # Set up jtreg if provided
    ${if jtreg != null then ''
      export JTREG_HOME="${jtreg}"
      echo "JTREG_HOME set to: $JTREG_HOME"
    '' else ''
      if [ -n "$JTREG_HOME" ]; then
        echo "JTREG_HOME already set to: $JTREG_HOME"
      else
        echo "JTREG_HOME not set (jtreg is optional)"
      fi
    ''}

    echo ""
    echo "OpenJDK build environment ready!"
    echo "BOOT_JDK_HOME set to: $BOOT_JDK_HOME"
    echo "OPENJDK_STUB_DIR set to: $STUB_DIR"
    if [ -n "$GTEST_HOME" ]; then
      echo "GTEST_HOME set to: $GTEST_HOME"
    fi
    echo ""
    echo "Stub scripts created in: $STUB_DIR"
    echo "  - stub-mig.sh"
    echo "  - stub-setfile.sh"
    echo ""
    echo "To build OpenJDK on macOS without Xcode:"
    echo ""
    echo "1. Navigate to jdk directory:"
    echo "   cd jdk"
    echo ""
    echo "2. Configure with workarounds for missing tools:"
    CONFIGURE_CMD="bash configure --with-boot-jdk=\$BOOT_JDK_HOME"
    [ -n "$JTREG_HOME" ] && CONFIGURE_CMD="$CONFIGURE_CMD --with-jtreg=\$JTREG_HOME"
    [ -n "$GTEST_HOME" ] && CONFIGURE_CMD="$CONFIGURE_CMD --with-gtest=\$GTEST_HOME"
    CONFIGURE_CMD="$CONFIGURE_CMD --enable-headless-only --disable-warnings-as-errors"
    CONFIGURE_CMD="$CONFIGURE_CMD METAL=/bin/echo METALLIB=/bin/echo"
    CONFIGURE_CMD="$CONFIGURE_CMD MIG=\$OPENJDK_STUB_DIR/stub-mig.sh SETFILE=\$OPENJDK_STUB_DIR/stub-setfile.sh"

    echo "   $CONFIGURE_CMD"

    if [ -z "$JTREG_HOME" ]; then
      echo ""
      echo "   To enable jtreg, set JTREG_HOME or pass jtreg parameter to nix-shell:"
      echo "   nix-shell --arg jtreg /path/to/jtreg"
    fi
    echo ""
    echo "3. Build:"
    echo "   make images"
    echo ""
    echo "4. Test the built JDK:"
    echo "   build/macosx-aarch64-server-release/jdk/bin/java --version"
  '';
}
